### ISSUE TITLE
Problem with copying "config.js" when using docker image instead of build

### ISSUE THREAD

**Issue by NoLooseEnds** [SillyWhale/rtorrent_flood#2]
Thanks for this.

I'm not sure if I did something wrong or not (I'm pretty new to docker), but I tried using the images instead of building them locally, and my modified "config.js" did not get included.

I ended up cloning the repo and building it locally via Docker, and then the modified "config.js" got included fine.

**Comment by vfricou** [comment]
Hello,

First, sorry for long time before response. 

Could you paste your docker-compose.yml file or your commands to launch stack please ?

**Comment by NoLooseEnds** [comment]
Sorry, not using this image any longer.
